name: .NET Core

on:
  repository_dispatch:
    types: [dotnet-test]

jobs:
  dotnet-test:
    runs-on: ubuntu-latest

    steps:
    # Build
    - uses: actions/checkout@v2

    - uses: actions/download-artifact@v2
      with:
        name: ${{ github.event.client_payload.build-artifact-name }}

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: test
      run: dotnet test --no-build --configuration Release
